general:
  train_fraction: 0.8

models_to_run:
  - linear_regression
  - svr
  - rf
  - xgb
  - lstm
  - bilstm
  - gru

model_params:
  linear_regression: {}
  svr:
    kernel: "rbf"
    C: 1.0
    epsilon: 0.1
  rf:
    n_estimators: 100
    max_depth: null
  xgb:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 3
  lstm:
    lookback: 20
    dropout: 0.2
    batch_size: 128
    learning_rate: 0.001
    optimizer: adam
    loss_function: mse
    epochs: 50
    activation: relu
    num_layers: 2
    neurons: 64
  bilstm:
    lookback: 20
    dropout: 0.2
    batch_size: 128
    learning_rate: 0.001
    optimizer: adam
    loss_function: mse
    epochs: 50
    activation: relu
    num_layers: 2
    neurons: 64
  gru:
    lookback: 20
    dropout: 0.2
    batch_size: 128
    learning_rate: 0.001
    optimizer: adam
    loss_function: mse
    epochs: 50
    activation: relu
    num_layers: 2
    neurons: 64

paths:
  data_file: "data/Microsoft_Stock.csv"
  output_dir: "outputs/"
